### ISSUE TITLE
FF Browser - Extra space appears after submit of activity

### ISSUE THREAD

**Issue by deshbirc** [comprodls/libs-frontend-ebook#105]
![extra-space inline-activity](https://cloud.githubusercontent.com/assets/10251562/9003680/8be351fc-378d-11e5-8f41-aa0c3d9ea392.png)

**Comment by deshbirc** [comment]
Also sometimes the whole page becomes BLANK / EMPTY (FF browser - intermittent)

**Comment by sushilarora** [comment]
Issue Fixed.
